[package]
name = "wgpu-clouds"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.29"
wgpu = "0.20"
pollster = "0.3"
bytemuck = { version = "1.14", features = ["derive"] }
cgmath = "0.18"
env_logger = "0.11"
log = "0.4"
